services:
  - type: web
    name: my-react-ts-app
    envVars:
      - key: NODE_VERSION
        value: 14
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    plan: free
